# Generated by Django 3.1.4 on 2021-01-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blindbook',
            fields=[
                ('bookno', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=1000, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'BLINDBOOK',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('sido_nm', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('gungu_nm', models.CharField(max_length=10)),
                ('libnumber', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CITY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('libno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('sido_nm', models.CharField(blank=True, max_length=10, null=True)),
                ('gungu_nm', models.CharField(blank=True, max_length=10, null=True)),
                ('close_day', models.CharField(blank=True, max_length=1000, null=True)),
                ('every_open', models.CharField(blank=True, max_length=10, null=True)),
                ('every_close', models.CharField(blank=True, max_length=10, null=True)),
                ('sat_open', models.CharField(blank=True, max_length=10, null=True)),
                ('sat_close', models.CharField(blank=True, max_length=10, null=True)),
                ('holiday_open', models.CharField(blank=True, max_length=10, null=True)),
                ('holiday_close', models.CharField(blank=True, max_length=10, null=True)),
                ('seats', models.IntegerField(blank=True, null=True)),
                ('books', models.IntegerField(blank=True, null=True)),
                ('loanable_books', models.IntegerField(blank=True, null=True)),
                ('loanable_days', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('site', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'library',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('sido_nm', models.CharField(blank=True, max_length=10, null=True)),
                ('gungu_nm', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'USER',
                'managed': False,
            },
        ),
    ]
